name = "gemini"
main = "src/cloudflare.ts"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[vars]
# Environment variables can be added here
# API_KEY = "your-api-key"

[[kv_namespaces]]
binding = "API_KEY_KV"
id = "ab18d5593fa64f7db10a608a2be01bf4"
